general.import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  "~/.config/alacritty/dracula.toml"
]

[font]
size=13
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }


[env]
WINIT_X11_SCALE_FACTOR="1.16"

[[keyboard.bindings]]
key = "H"
mods = "Control|Shift"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "n"
mode = "Vi|~Search"
action = "Down"

[[keyboard.bindings]]
key = "e"
mode = "Vi|~Search"
action = "Up"

[[keyboard.bindings]]
key = "i"
mode = "Vi|~Search"
action = "Right"

[[keyboard.bindings]]
key = "u"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "a"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "q"
mode = "Vi|~Search"
action = "ToggleViMode"

[[keyboard.bindings]]
key = "Escape"
mode = "Vi|~Search"
action = "ToggleViMode"
