#!/bin/bash

set -o pipefail

# Directory
_SCREENSHOT_DIR_=$HOME/Pictures/Screenshots

function check() {
    if [[ $? -eq 1 && ${PIPESTATUS[0]} -eq 1 ]]; then
        dunstify -u critical -t 3000 -a "Screenshot Tool" "Failed"
        exit 1
    fi
}

# Check save directory
function check_dir() {
    if [[ ! -d "$_SCREENSHOT_DIR_" ]]; then
        mkdir -p "$_SCREENSHOT_DIR_"
    fi
}

function take_screenshot() {
    check_dir
    
    _timestamp_=$(date +%s)
    _screenshot_command_="$1"
    _notif_message_="$2"
    
    # Execute screenshot command
    $_screenshot_command_ $_SCREENSHOT_DIR_/${_timestamp_}.png > /dev/null 2>&1
    check
    
    # Send notification
    dunstify -t 3000 "Screenshot Tool" "$_notif_message_" -a "Screenshot Tool"
}

# Check parameters
if [ -z "$1" ] || ([ "$1" != 'full' ] && [ "$1" != 'area' ]); then
    echo "
    Parameter required:
    area    - Area screenshot
    full    - Full screenshot
    Example:
    ./screensht area
    ./screensht full
    "
elif [ "$1" = 'full' ]; then
    msg="Full screenshot saved and copied to clipboard!"
    take_screenshot 'grimblast copysave output' "${msg}"
elif [ "$1" = 'area' ]; then
    msg='Area screenshot saved and copied to clipboard!'
    take_screenshot 'grimblast copysave area' "${msg}"
fi
