# the default speed for mouse movement and scrolling
baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

comboTime: 100

# the rest of the config defines the layers with their bindings
layers:
  # the first layer is active at start
  - name: initial
    bindings:
      # when tab is held and another key pressed, activate mouse layer
      # tab: tap-hold-next tab ; toggle-layer mouse ; 500
      # when a is held for 300ms, activate mouse layer
      # a: tap-hold a ; toggle-layer mouse ; 500
      # when leftalt+a, activate mouse layer
      leftalt+a: layer mouse
  # a layer for mouse movement
  - name: mouse
  # enterCommand: "notify-send 'mouseless' 'mouse layer entered'"
  # exitCommand: "notify-send 'mouseless' 'mouse layer exited'"
    enterCommand: "touch $HOME/Templates/mouse.tmp; pkill -RTMIN+7 waybar"
    exitCommand: "rm $HOME/Templates/mouse.tmp; pkill -RTMIN+7 waybar"
    # when true, keys that are not mapped keep their original meaning
    bindings:
      # quit mouse layer
      q: layer initial
      i: layer initial
      # keep the mouse layer active
      space: layer mouse
      l: move  1  0
      h: move -1  0
      j: move  0  1
      k: move  0 -1
      p: scroll up
      n: scroll down
      c: speed 4.0
      e: speed 0.3
      capslock: speed 0.1
      f: button left
      d: button middle
      s: button right

